#!/bin/bash

#Fonts
cp *.ttf output

#English
/usr/bin/pandoc src/resume_en.md -o output/ben_fedidat_resume.html -t html5 \
  -f markdown+smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles_en.html \
  --include-before-body=_pandoc/header_en.html \
  --include-after-body=_pandoc/footer_en.html \
  --variable="pagetitle:Resume :: Ben Fedidat"

/usr/bin/pandoc src/resume_en.md -o output/ben_fedidat_resume.odt --reference-doc=_pandoc/reference_en.odt

libreoffice --headless --convert-to doc output/ben_fedidat_resume.odt --outdir output
libreoffice --headless --convert-to pdf output/ben_fedidat_resume.odt --outdir output

#French
/usr/bin/pandoc src/resume_fr.md -o output/ben_fedidat_resume_fr.html -t html5 \
  -f markdown+smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles_fr.html \
  --include-before-body=_pandoc/header_fr.html \
  --include-after-body=_pandoc/footer_fr.html \
  --variable="pagetitle:CV :: Ben Fedidat"

/usr/bin/pandoc src/resume_fr.md -o output/ben_fedidat_resume_fr.odt --reference-doc=_pandoc/reference_fr.odt

libreoffice --headless --convert-to doc output/ben_fedidat_resume_fr.odt --outdir output
libreoffice --headless --convert-to pdf output/ben_fedidat_resume_fr.odt --outdir output

#Hebrew
/usr/bin/pandoc src/resume_he.md -o output/ben_fedidat_resume_he.html -t html5 \
	-V dir=rtl \
  -f markdown+smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles_he.html \
  --include-before-body=_pandoc/header_he.html \
  --include-after-body=_pandoc/footer_he.html \
  --variable="pagetitle:קורות חיים :: בן פדידה"

/usr/bin/pandoc src/resume_he.md -o output/ben_fedidat_resume_he.odt --reference-doc=_pandoc/reference_he.odt

libreoffice --headless --convert-to doc output/ben_fedidat_resume_he.odt --outdir output
libreoffice --headless --convert-to pdf output/ben_fedidat_resume_he.odt --outdir output

echo "copying"
cp output/* /home/ben/Desktop/dev/HexoSite/source/cv